const offers = [
    { 
        uid: 1, 
        title: 'URGENT: Need help with organizing a charity event', 
        description: 'We arere urgently seeking assistance to organize a meaningful charity event in our community.This event aims to make a real difference in the lives of those in need.We need enthusiastic volunteers who can help with planning, coordination, and execution.Your support will help us bring hope and joy to many individuals who deserve our care and support.Lets come together and make a positive impact! Looking forward to your participation and generous contributions.', 
        category: 'Charity', 
        country: 'Germany', 
        city: 'Berlin', 
        date: '2024-07-01', 
        budget: 0, 
        frequency: 'Once', 
        skillsReq: false, 
        likes: 31, 
        dislikes: 17,
        part: 3,
        partMax: 20  
    },
    { 
        uid: 2, 
        title: 'Favour needed: in need of help moving stuff', 
        description: 'I am looking for a helping hand to assist with moving some belongings.It is a bit of a task, and any assistance would be greatly appreciated. We need help with packing, loading, and unloading items safely. If you are available and willing to lend a hand, please reach out.Your support will make a significant difference during this transition.Looking forward to hearing from you soon!', 
        category: 'Moving', 
        country: 'Bulgaria', 
        city: 'Sofia', 
        date: '2024-08-01', 
        budget: 50, 
        frequency: 'Once', 
        skillsReq: false, 
        likes: 0, 
        dislikes: 9,
        part: 0,
        partMax: 2  
    },
    { 
        uid: 3, 
        title: 'QUICK MONEY: hmu to start', 
        description: 'If you are looking to earn some quick cash, look no further! I have an opportunity that could be perfect for you.Get in touch with me to get started on a simple yet rewarding task that promises quick earnings. Do not miss out on this chance to make some extra money quickly and easily. Reach out now to seize this opportunity!', 
        category: 'Other', 
        country: 'Cameroon', 
        city: 'Douala', 
        date: '2024-08-01', 
        budget: 1000, 
        frequency: 'Weekly', 
        skillsReq: false, 
        likes: 32, 
        dislikes: 11,
        part: 9,
        partMax: 10  
    },
    { 
        uid: 1, 
        title: 'Need to graduate: Please finish my final project',
        description: 'I am reaching out for assistance to complete my final project and graduate on time.Due to unforeseen circumstances, I am unable to finish it alone. If you have the expertise and willingness to help with this crucial task, please get in touch. PLEASE DO NOT LET MR. MOHAMMED SEE THIS. Lets work together to ensure success and completion.Thank you for considering this request.', 
        category: 'Academia', 
        country: 'Germany', 
        city: 'Munich', 
        date: '2024-07-15', 
        budget: 100, 
        frequency: 'Once', 
        skillsReq: true, 
        likes: 1, 
        dislikes: 2,
        part: 0,
        partMax: 1  
    },
    { 
        uid: 2, 
        title: 'In search of driver', 
        description: 'I am currently in need of a reliable driver to assist with transportation needs.If you have a valid drivers license and a dependable vehicle, I would greatly appreciate your assistance. This role involves safe and efficient transportation for various tasks and errands. If you are interested in earning some extra income while providing valuable support, please reach out to discuss further details.Looking forward to hearing from you soon!', 
        category: 'Driving', 
        country: 'Bulgaria', 
        city: 'Plovdiv', 
        date: '2024-08-15', 
        budget: 100, 
        frequency: 'Once', 
        skillsReq: true, 
        likes: 5, 
        dislikes: 2,
        part: 0,
        partMax: 1  
    }
];

module.exports = offers;