const offers = [
    {
        uid: 1,
        title: 'URGENT: Need help with organizing a charity event',
        description: 'We are urgently seeking assistance to organize a meaningful charity event in our community. This event aims to make a real difference in the lives of those in need. We need enthusiastic volunteers who can help with planning, coordination, and execution. Your support will help us bring hope and joy to many individuals who deserve our care and support. Let\'s come together and make a positive impact! Looking forward to your participation and generous contributions.',
        category: 'Charity',
        country: 'Germany',
        city: 'Berlin',
        date: '2024-07-01',
        budget: 0,
        frequency: 'Once',
        skillsReq: false,
        likes: 31,
        dislikes: 17,
        part: 3,
        partMax: 20
    },
    {
        uid: 2,
        title: 'Favour needed: in need of help moving stuff',
        description: 'I am looking for a helping hand to assist with moving some belongings. It is a bit of a task, and any assistance would be greatly appreciated. We need help with packing, loading, and unloading items safely. If you are available and willing to lend a hand, please reach out. Your support will make a significant difference during this transition. Looking forward to hearing from you soon!',
        category: 'Moving',
        country: 'Bulgaria',
        city: 'Sofia',
        date: '2024-08-01',
        budget: 50,
        frequency: 'Once',
        skillsReq: false,
        likes: 0,
        dislikes: 9,
        part: 0,
        partMax: 2
    },
    {
        uid: 3,
        title: 'QUICK MONEY: hmu to start',
        description: 'If you are looking to earn some quick cash, look no further! I have an opportunity that could be perfect for you. Get in touch with me to get started on a simple yet rewarding task that promises quick earnings. Do not miss out on this chance to make some extra money quickly and easily. Reach out now to seize this opportunity!',
        category: 'Other',
        country: 'Bulgaria',
        city: 'Plovdiv',
        date: '2024-08-01',
        budget: 1000,
        frequency: 'Weekly',
        skillsReq: false,
        likes: 32,
        dislikes: 11,
        part: 9,
        partMax: 10
    },
    {
        uid: 1,
        title: 'Need to graduate: Please finish my final project',
        description: 'I am reaching out for assistance to complete my final project and graduate on time. Due to unforeseen circumstances, I am unable to finish it alone. If you have the expertise and willingness to help with this crucial task, please get in touch. PLEASE DO NOT LET MR. MOHAMMED SEE THIS. Let\'s work together to ensure success and completion. Thank you for considering this request.',
        category: 'Academia',
        country: 'Germany',
        city: 'Munich',
        date: '2024-07-15',
        budget: 100,
        frequency: 'Once',
        skillsReq: true,
        likes: 1,
        dislikes: 2,
        part: 0,
        partMax: 1
    },
    {
        uid: 2,
        title: 'In search of driver',
        description: 'I am currently in need of a reliable driver to assist with transportation needs. If you have a valid driver\'s license and a dependable vehicle, I would greatly appreciate your assistance. This role involves safe and efficient transportation for various tasks and errands. If you are interested in earning some extra income while providing valuable support, please reach out to discuss further details. Looking forward to hearing from you soon!',
        category: 'Driving',
        country: 'Bulgaria',
        city: 'Plovdiv',
        date: '2024-08-15',
        budget: 100,
        frequency: 'Once',
        skillsReq: true,
        likes: 5,
        dislikes: 2,
        part: 0,
        partMax: 1
    },
    {
        uid: 1,
        title: 'Help needed: Painting a room',
        description: 'I am looking for someone to help paint a room in my house. The job includes preparing the room, applying primer and paint, and cleaning up afterward. If you have experience with painting and are available to assist this weekend, please contact me. Your help will make a big difference in freshening up my home.',
        category: 'Moving',
        country: 'Germany',
        city: 'Berlin',
        date: '2024-08-08',
        budget: 100,
        frequency: 'Once',
        skillsReq: true,
        likes: 5,
        dislikes: 1,
        part: 0,
        partMax: 1
    },
    {
        uid: 2,
        title: 'Looking for help with home decluttering',
        description: 'I need assistance with decluttering my home. This includes sorting through items, organizing them, and deciding what to keep or donate. If you have a knack for organizing and can help out this weekend, please contact me. Your help will make my home more organized and livable.',
        category: 'Moving',
        country: 'Bulgaria',
        city: 'Sofia',
        date: '2024-08-09',
        budget: 90,
        frequency: 'Once',
        skillsReq: false,
        likes: 7,
        dislikes: 2,
        part: 0,
        partMax: 1
    },
    {
        uid: 3,
        title: 'Help needed for assembling furniture',
        description: 'I recently bought new furniture and need help assembling it. This includes putting together chairs, tables, and other items. If you have experience with furniture assembly and are available this week, please reach out. Your assistance will be invaluable in setting up my new furniture.',
        category: 'Moving',
        country: 'Germany',
        city: 'Munich',
        date: '2024-08-03',
        budget: 80,
        frequency: 'Once',
        skillsReq: true,
        likes: 9,
        dislikes: 1,
        part: 0,
        partMax: 1
    },
    {
        uid: 1,
        title: 'Help with organizing a garage sale',
        description: 'I am organizing a garage sale and need help setting up tables, displaying items, and managing the sale. If you have experience with garage sales and can help on August 25th, please get in touch. Your help will make the sale run smoothly and be more successful.',
        category: 'Other',
        country: 'Germany',
        city: 'Berlin',
        date: '2024-08-25',
        budget: 60,
        frequency: 'Once',
        skillsReq: false,
        likes: 4,
        dislikes: 0,
        part: 0,
        partMax: 1
    },
    {
        uid: 2,
        title: 'Need a photographer for an event',
        description: 'I am hosting a small event and need a photographer to capture the moments. The job includes taking photos of guests, the venue, and key moments throughout the event. If you have experience with event photography and are available on August 15th, please reach out. Your photos will be cherished by all attendees.',
        category: 'Other',
        country: 'Germany',
        city: 'Berlin',
        date: '2024-08-15',
        budget: 200,
        frequency: 'Once',
        skillsReq: true,
        likes: 12,
        dislikes: 3,
        part: 0,
        partMax: 1
    },
    {
        uid: 3,
        title: 'Need help with language translation',
        description: 'I need assistance translating documents from Spanish to English. If you are fluent in both languages and can help with accurate translation, please contact me. This is an important task for an upcoming project and your help will be greatly valued.',
        category: 'Other',
        country: 'Germany',
        city: 'Hamburg',
        date: '2024-08-10',
        budget: 90,
        frequency: 'Once',
        skillsReq: true,
        likes: 6,
        dislikes: 2,
        part: 0,
        partMax: 1
    }
];

module.exports = offers;